export const countries = [
  { value: 'AF', label: 'Afghanistan', dialCode: '93', flag: '🇦🇫' },
  { value: 'AL', label: 'Albania', dialCode: '355', flag: '🇦🇱' },
  { value: 'DZ', label: 'Algeria', dialCode: '213', flag: '🇩🇿' },
  { value: 'AS', label: 'American Samoa', dialCode: '1-684', flag: '🇦🇸' },
  { value: 'AD', label: 'Andorra', dialCode: '376', flag: '🇦🇩' },
  { value: 'AO', label: 'Angola', dialCode: '244', flag: '🇦🇴' },
  { value: 'AI', label: 'Anguilla', dialCode: '1-264', flag: '🇦🇮' },
  { value: 'AQ', label: 'Antarctica', dialCode: '672', flag: '🇦🇶' },
  { value: 'AG', label: 'Antigua and Barbuda', dialCode: '1-268', flag: '🇦🇬' },
  { value: 'AR', label: 'Argentina', dialCode: '54', flag: '🇦🇷' },
  { value: 'AM', label: 'Armenia', dialCode: '374', flag: '🇦🇲' },
  { value: 'AW', label: 'Aruba', dialCode: '297', flag: '🇦🇼' },
  { value: 'AU', label: 'Australia', dialCode: '61', flag: '🇦🇺' },
  { value: 'AT', label: 'Austria', dialCode: '43', flag: '🇦🇹' },
  { value: 'AZ', label: 'Azerbaijan', dialCode: '994', flag: '🇦🇿' },
  { value: 'BS', label: 'Bahamas', dialCode: '1-242', flag: '🇧🇸' },
  { value: 'BH', label: 'Bahrain', dialCode: '973', flag: '🇧🇭' },
  { value: 'BD', label: 'Bangladesh', dialCode: '880', flag: '🇧🇩' },
  { value: 'BB', label: 'Barbados', dialCode: '1-246', flag: '🇧🇧' },
  { value: 'BY', label: 'Belarus', dialCode: '375', flag: '🇧🇾' },
  { value: 'BE', label: 'Belgium', dialCode: '32', flag: '🇧🇪' },
  { value: 'BZ', label: 'Belize', dialCode: '501', flag: '🇧🇿' },
  { value: 'BJ', label: 'Benin', dialCode: '229', flag: '🇧🇯' },
  { value: 'BM', label: 'Bermuda', dialCode: '1-441', flag: '🇧🇲' },
  { value: 'BT', label: 'Bhutan', dialCode: '975', flag: '🇧🇹' },
  { value: 'BO', label: 'Bolivia', dialCode: '591', flag: '🇧🇴' },
  { value: 'BA', label: 'Bosnia and Herzegovina', dialCode: '387', flag: '🇧🇦' },
  { value: 'BW', label: 'Botswana', dialCode: '267', flag: '🇧🇼' },
  { value: 'BR', label: 'Brazil', dialCode: '55', flag: '🇧🇷' },
  { value: 'IO', label: 'British Indian Ocean Territory', dialCode: '246', flag: '🇮🇴' },
  { value: 'VG', label: 'British Virgin Islands', dialCode: '1-284', flag: '🇻🇬' },
  { value: 'BN', label: 'Brunei', dialCode: '673', flag: '🇧🇳' },
  { value: 'BG', label: 'Bulgaria', dialCode: '359', flag: '🇧🇬' },
  { value: 'BF', label: 'Burkina Faso', dialCode: '226', flag: '🇧🇫' },
  { value: 'BI', label: 'Burundi', dialCode: '257', flag: '🇧🇮' },
  { value: 'KH', label: 'Cambodia', dialCode: '855', flag: '🇰🇭' },
  { value: 'CM', label: 'Cameroon', dialCode: '237', flag: '🇨🇲' },
  { value: 'CA', label: 'Canada', dialCode: '1', flag: '🇨🇦' },
  { value: 'CV', label: 'Cape Verde', dialCode: '238', flag: '🇨🇻' },
  { value: 'KY', label: 'Cayman Islands', dialCode: '1-345', flag: '🇰🇾' },
  { value: 'CF', label: 'Central African Republic', dialCode: '236', flag: '🇨🇫' },
  { value: 'TD', label: 'Chad', dialCode: '235', flag: '🇹🇩' },
  { value: 'CL', label: 'Chile', dialCode: '56', flag: '🇨🇱' },
  { value: 'CN', label: 'China', dialCode: '86', flag: '🇨🇳' },
  { value: 'CX', label: 'Christmas Island', dialCode: '61', flag: '🇨🇽' },
  { value: 'CC', label: 'Cocos Islands', dialCode: '61', flag: '🇨🇨' },
  { value: 'CO', label: 'Colombia', dialCode: '57', flag: '🇨🇴' },
  { value: 'KM', label: 'Comoros', dialCode: '269', flag: '🇰🇲' },
  { value: 'CK', label: 'Cook Islands', dialCode: '682', flag: '🇨🇰' },
  { value: 'CR', label: 'Costa Rica', dialCode: '506', flag: '🇨🇷' },
  { value: 'HR', label: 'Croatia', dialCode: '385', flag: '🇭🇷' },
  { value: 'CU', label: 'Cuba', dialCode: '53', flag: '🇨🇺' },
  { value: 'CW', label: 'Curacao', dialCode: '599', flag: '🇨🇼' },
  { value: 'CY', label: 'Cyprus', dialCode: '357', flag: '🇨🇾' },
  { value: 'CZ', label: 'Czech Republic', dialCode: '420', flag: '🇨🇿' },
  { value: 'CD', label: 'Democratic Republic of the Congo', dialCode: '243', flag: '🇨🇩' },
  { value: 'DK', label: 'Denmark', dialCode: '45', flag: '🇩🇰' },
  { value: 'DJ', label: 'Djibouti', dialCode: '253', flag: '🇩🇯' },
  { value: 'DM', label: 'Dominica', dialCode: '1-767', flag: '🇩🇲' },
  { value: 'DO', label: 'Dominican Republic', dialCode: '1-809', flag: '🇩🇴' },
  { value: 'TL', label: 'East Timor', dialCode: '670', flag: '🇹🇱' },
  { value: 'EC', label: 'Ecuador', dialCode: '593', flag: '🇪🇨' },
  { value: 'EG', label: 'Egypt', dialCode: '20', flag: '🇪🇬' },
  { value: 'SV', label: 'El Salvador', dialCode: '503', flag: '🇸🇻' },
  { value: 'GQ', label: 'Equatorial Guinea', dialCode: '240', flag: '🇬🇶' },
  { value: 'ER', label: 'Eritrea', dialCode: '291', flag: '🇪🇷' },
  { value: 'EE', label: 'Estonia', dialCode: '372', flag: '🇪🇪' },
  { value: 'ET', label: 'Ethiopia', dialCode: '251', flag: '🇪🇹' },
  { value: 'FK', label: 'Falkland Islands', dialCode: '500', flag: '🇫🇰' },
  { value: 'FO', label: 'Faroe Islands', dialCode: '298', flag: '🇫🇴' },
  { value: 'FJ', label: 'Fiji', dialCode: '679', flag: '🇫🇯' },
  { value: 'FI', label: 'Finland', dialCode: '358', flag: '🇫🇮' },
  { value: 'FR', label: 'France', dialCode: '33', flag: '🇫🇷' },
  { value: 'PF', label: 'French Polynesia', dialCode: '689', flag: '🇵🇫' },
  { value: 'GA', label: 'Gabon', dialCode: '241', flag: '🇬🇦' },
  { value: 'GM', label: 'Gambia', dialCode: '220', flag: '🇬🇲' },
  { value: 'GE', label: 'Georgia', dialCode: '995', flag: '🇬🇪' },
  { value: 'DE', label: 'Germany', dialCode: '49', flag: '🇩🇪' },
  { value: 'GH', label: 'Ghana', dialCode: '233', flag: '🇬🇭' },
  { value: 'GI', label: 'Gibraltar', dialCode: '350', flag: '🇬🇮' },
  { value: 'GR', label: 'Greece', dialCode: '30', flag: '🇬🇷' },
  { value: 'GL', label: 'Greenland', dialCode: '299', flag: '🇬🇱' },
  { value: 'GD', label: 'Grenada', dialCode: '1-473', flag: '🇬🇩' },
  { value: 'GU', label: 'Guam', dialCode: '1-671', flag: '🇬🇺' },
  { value: 'GT', label: 'Guatemala', dialCode: '502', flag: '🇬🇹' },
  { value: 'GG', label: 'Guernsey', dialCode: '44-1481', flag: '🇬🇬' },
  { value: 'GN', label: 'Guinea', dialCode: '224', flag: '🇬🇳' },
  { value: 'GW', label: 'Guinea-Bissau', dialCode: '245', flag: '🇬🇼' },
  { value: 'GY', label: 'Guyana', dialCode: '592', flag: '🇬🇾' },
  { value: 'HT', label: 'Haiti', dialCode: '509', flag: '🇭🇹' },
  { value: 'HN', label: 'Honduras', dialCode: '504', flag: '🇭🇳' },
  { value: 'HK', label: 'Hong Kong', dialCode: '852', flag: '🇭🇰' },
  { value: 'HU', label: 'Hungary', dialCode: '36', flag: '🇭🇺' },
  { value: 'IS', label: 'Iceland', dialCode: '354', flag: '🇮🇸' },
  { value: 'IN', label: 'India', dialCode: '91', flag: '🇮🇳' },
  { value: 'ID', label: 'Indonesia', dialCode: '62', flag: '🇮🇩' },
  { value: 'IR', label: 'Iran', dialCode: '98', flag: '🇮🇷' },
  { value: 'IQ', label: 'Iraq', dialCode: '964', flag: '🇮🇶' },
  { value: 'IE', label: 'Ireland', dialCode: '353', flag: '🇮🇪' },
  { value: 'IM', label: 'Isle of Man', dialCode: '44-1624', flag: '🇮🇲' },
  { value: 'IL', label: 'Israel', dialCode: '972', flag: '🇮🇱' },
  { value: 'IT', label: 'Italy', dialCode: '39', flag: '🇮🇹' },
  { value: 'CI', label: 'Ivory Coast', dialCode: '225', flag: '🇨🇮' },
  { value: 'JM', label: 'Jamaica', dialCode: '1-876', flag: '🇯🇲' },
  { value: 'JP', label: 'Japan', dialCode: '81', flag: '🇯🇵' },
  { value: 'JE', label: 'Jersey', dialCode: '44-1534', flag: '🇯🇪' },
  { value: 'JO', label: 'Jordan', dialCode: '962', flag: '🇯🇴' },
  { value: 'KZ', label: 'Kazakhstan', dialCode: '7', flag: '🇰🇿' },
  { value: 'KE', label: 'Kenya', dialCode: '254', flag: '🇰🇪' },
  { value: 'KI', label: 'Kiribati', dialCode: '686', flag: '🇰🇮' },
  { value: 'XK', label: 'Kosovo', dialCode: '383', flag: '🇽🇰' },
  { value: 'KW', label: 'Kuwait', dialCode: '965', flag: '🇰🇼' },
  { value: 'KG', label: 'Kyrgyzstan', dialCode: '996', flag: '🇰🇬' },
  { value: 'LA', label: 'Laos', dialCode: '856', flag: '🇱🇦' },
  { value: 'LV', label: 'Latvia', dialCode: '371', flag: '🇱🇻' },
  { value: 'LB', label: 'Lebanon', dialCode: '961', flag: '🇱🇧' },
  { value: 'LS', label: 'Lesotho', dialCode: '266', flag: '🇱🇸' },
  { value: 'LR', label: 'Liberia', dialCode: '231', flag: '🇱🇷' },
  { value: 'LY', label: 'Libya', dialCode: '218', flag: '🇱🇾' },
  { value: 'LI', label: 'Liechtenstein', dialCode: '423', flag: '🇱🇮' },
  { value: 'LT', label: 'Lithuania', dialCode: '370', flag: '🇱🇹' },
  { value: 'LU', label: 'Luxembourg', dialCode: '352', flag: '🇱🇺' },
  { value: 'MO', label: 'Macau', dialCode: '853', flag: '🇲🇴' },
  { value: 'MK', label: 'Macedonia', dialCode: '389', flag: '🇲🇰' },
  { value: 'MG', label: 'Madagascar', dialCode: '261', flag: '🇲🇬' },
  { value: 'MW', label: 'Malawi', dialCode: '265', flag: '🇲🇼' },
  { value: 'MY', label: 'Malaysia', dialCode: '60', flag: '🇲🇾' },
  { value: 'MV', label: 'Maldives', dialCode: '960', flag: '🇲🇻' },
  { value: 'ML', label: 'Mali', dialCode: '223', flag: '🇲🇱' },
  { value: 'MT', label: 'Malta', dialCode: '356', flag: '🇲🇹' },
  { value: 'MH', label: 'Marshall Islands', dialCode: '692', flag: '🇲🇭' },
  { value: 'MR', label: 'Mauritania', dialCode: '222', flag: '🇲🇷' },
  { value: 'MU', label: 'Mauritius', dialCode: '230', flag: '🇲🇺' },
  { value: 'YT', label: 'Mayotte', dialCode: '262', flag: '🇾🇹' },
  { value: 'MX', label: 'Mexico', dialCode: '52', flag: '🇲🇽' },
  { value: 'FM', label: 'Micronesia', dialCode: '691', flag: '🇫🇲' },
  { value: 'MD', label: 'Moldova', dialCode: '373', flag: '🇲🇩' },
  { value: 'MC', label: 'Monaco', dialCode: '377', flag: '🇲🇨' },
  { value: 'MN', label: 'Mongolia', dialCode: '976', flag: '🇲🇳' },
  { value: 'ME', label: 'Montenegro', dialCode: '382', flag: '🇲🇪' },
  { value: 'MS', label: 'Montserrat', dialCode: '1-664', flag: '🇲🇸' },
  { value: 'MA', label: 'Morocco', dialCode: '212', flag: '🇲🇦' },
  { value: 'MZ', label: 'Mozambique', dialCode: '258', flag: '🇲🇿' },
  { value: 'MM', label: 'Myanmar', dialCode: '95', flag: '🇲🇲' },
  { value: 'NA', label: 'Namibia', dialCode: '264', flag: '🇳🇦' },
  { value: 'NR', label: 'Nauru', dialCode: '674', flag: '🇳🇷' },
  { value: 'NP', label: 'Nepal', dialCode: '977', flag: '🇳🇵' },
  { value: 'NL', label: 'Netherlands', dialCode: '31', flag: '🇳🇱' },
  { value: 'AN', label: 'Netherlands Antilles', dialCode: '599', flag: '🇦🇳' },
  { value: 'NC', label: 'New Caledonia', dialCode: '687', flag: '🇳🇨' },
  { value: 'NZ', label: 'New Zealand', dialCode: '64', flag: '🇳🇿' },
  { value: 'NI', label: 'Nicaragua', dialCode: '505', flag: '🇳🇮' },
  { value: 'NE', label: 'Niger', dialCode: '227', flag: '🇳🇪' },
  { value: 'NG', label: 'Nigeria', dialCode: '234', flag: '🇳🇬' },
  { value: 'NU', label: 'Niue', dialCode: '683', flag: '🇳🇺' },
  { value: 'KP', label: 'North Korea', dialCode: '850', flag: '🇰🇵' },
  { value: 'MP', label: 'Northern Mariana Islands', dialCode: '1-670', flag: '🇲🇵' },
  { value: 'NO', label: 'Norway', dialCode: '47', flag: '🇳🇴' },
  { value: 'OM', label: 'Oman', dialCode: '968', flag: '🇴🇲' },
  { value: 'PK', label: 'Pakistan', dialCode: '92', flag: '🇵🇰' },
  { value: 'PW', label: 'Palau', dialCode: '680', flag: '🇵🇼' },
  { value: 'PS', label: 'Palestine', dialCode: '970', flag: '🇵🇸' },
  { value: 'PA', label: 'Panama', dialCode: '507', flag: '🇵🇦' },
  { value: 'PG', label: 'Papua New Guinea', dialCode: '675', flag: '🇵🇬' },
  { value: 'PY', label: 'Paraguay', dialCode: '595', flag: '🇵🇾' },
  { value: 'PE', label: 'Peru', dialCode: '51', flag: '🇵🇪' },
  { value: 'PH', label: 'Philippines', dialCode: '63', flag: '🇵🇭' },
  { value: 'PN', label: 'Pitcairn', dialCode: '64', flag: '🇵🇳' },
  { value: 'PL', label: 'Poland', dialCode: '48', flag: '🇵🇱' },
  { value: 'PT', label: 'Portugal', dialCode: '351', flag: '🇵🇹' },
  { value: 'PR', label: 'Puerto Rico', dialCode: '1-787', flag: '🇵🇷' },
  { value: 'QA', label: 'Qatar', dialCode: '974', flag: '🇶🇦' },
  { value: 'CG', label: 'Republic of the Congo', dialCode: '242', flag: '🇨🇬' },
  { value: 'RE', label: 'Reunion', dialCode: '262', flag: '🇷🇪' },
  { value: 'RO', label: 'Romania', dialCode: '40', flag: '🇷🇴' },
  { value: 'RU', label: 'Russia', dialCode: '7', flag: '🇷🇺' },
  { value: 'RW', label: 'Rwanda', dialCode: '250', flag: '🇷🇼' },
  { value: 'BL', label: 'Saint Barthelemy', dialCode: '590', flag: '🇧🇱' },
  { value: 'SH', label: 'Saint Helena', dialCode: '290', flag: '🇸🇭' },
  { value: 'KN', label: 'Saint Kitts and Nevis', dialCode: '1-869', flag: '🇰🇳' },
  { value: 'LC', label: 'Saint Lucia', dialCode: '1-758', flag: '🇱🇨' },
  { value: 'MF', label: 'Saint Martin', dialCode: '590', flag: '🇲🇫' },
  { value: 'PM', label: 'Saint Pierre and Miquelon', dialCode: '508', flag: '🇵🇲' },
  { value: 'VC', label: 'Saint Vincent and the Grenadines', dialCode: '1-784', flag: '🇻🇨' },
  { value: 'WS', label: 'Samoa', dialCode: '685', flag: '🇼🇸' },
  { value: 'SM', label: 'San Marino', dialCode: '378', flag: '🇸🇲' },
  { value: 'ST', label: 'Sao Tome and Principe', dialCode: '239', flag: '🇸🇹' },
  { value: 'SA', label: 'Saudi Arabia', dialCode: '966', flag: '🇸🇦' },
  { value: 'SN', label: 'Senegal', dialCode: '221', flag: '🇸🇳' },
  { value: 'RS', label: 'Serbia', dialCode: '381', flag: '🇷🇸' },
  { value: 'SC', label: 'Seychelles', dialCode: '248', flag: '🇸🇨' },
  { value: 'SL', label: 'Sierra Leone', dialCode: '232', flag: '🇸🇱' },
  { value: 'SG', label: 'Singapore', dialCode: '65', flag: '🇸🇬' },
  { value: 'SX', label: 'Sint Maarten', dialCode: '1-721', flag: '🇸🇽' },
  { value: 'SK', label: 'Slovakia', dialCode: '421', flag: '🇸🇰' },
  { value: 'SI', label: 'Slovenia', dialCode: '386', flag: '🇸🇮' },
  { value: 'SB', label: 'Solomon Islands', dialCode: '677', flag: '🇸🇧' },
  { value: 'SO', label: 'Somalia', dialCode: '252', flag: '🇸🇴' },
  { value: 'ZA', label: 'South Africa', dialCode: '27', flag: '🇿🇦' },
  { value: 'KR', label: 'South Korea', dialCode: '82', flag: '🇰🇷' },
  { value: 'SS', label: 'South Sudan', dialCode: '211', flag: '🇸🇸' },
  { value: 'ES', label: 'Spain', dialCode: '34', flag: '🇪🇸' },
  { value: 'LK', label: 'Sri Lanka', dialCode: '94', flag: '🇱🇰' },
  { value: 'SD', label: 'Sudan', dialCode: '249', flag: '🇸🇩' },
  { value: 'SR', label: 'Suriname', dialCode: '597', flag: '🇸🇷' },
  { value: 'SJ', label: 'Svalbard and Jan Mayen', dialCode: '47', flag: '🇸🇯' },
  { value: 'SZ', label: 'Swaziland', dialCode: '268', flag: '🇸🇿' },
  { value: 'SE', label: 'Sweden', dialCode: '46', flag: '🇸🇪' },
  { value: 'CH', label: 'Switzerland', dialCode: '41', flag: '🇨🇭' },
  { value: 'SY', label: 'Syria', dialCode: '963', flag: '🇸🇾' },
  { value: 'TW', label: 'Taiwan', dialCode: '886', flag: '🇹🇼' },
  { value: 'TJ', label: 'Tajikistan', dialCode: '992', flag: '🇹🇯' },
  { value: 'TZ', label: 'Tanzania', dialCode: '255', flag: '🇹🇿' },
  { value: 'TH', label: 'Thailand', dialCode: '66', flag: '🇹🇭' },
  { value: 'TG', label: 'Togo', dialCode: '228', flag: '🇹🇬' },
  { value: 'TK', label: 'Tokelau', dialCode: '690', flag: '🇹🇰' },
  { value: 'TO', label: 'Tonga', dialCode: '676', flag: '🇹🇴' },
  { value: 'TT', label: 'Trinidad and Tobago', dialCode: '1-868', flag: '🇹🇹' },
  { value: 'TN', label: 'Tunisia', dialCode: '216', flag: '🇹🇳' },
  { value: 'TR', label: 'Turkey', dialCode: '90', flag: '🇹🇷' },
  { value: 'TM', label: 'Turkmenistan', dialCode: '993', flag: '🇹🇲' },
  { value: 'TC', label: 'Turks and Caicos Islands', dialCode: '1-649', flag: '🇹🇨' },
  { value: 'TV', label: 'Tuvalu', dialCode: '688', flag: '🇹🇻' },
  { value: 'VI', label: 'U.S. Virgin Islands', dialCode: '1-340', flag: '🇻🇮' },
  { value: 'UG', label: 'Uganda', dialCode: '256', flag: '🇺🇬' },
  { value: 'UA', label: 'Ukraine', dialCode: '380', flag: '🇺🇦' },
  { value: 'AE', label: 'United Arab Emirates', dialCode: '971', flag: '🇦🇪' },
  { value: 'GB', label: 'United Kingdom', dialCode: '44', flag: '🇬🇧' },
  { value: 'US', label: 'United States', dialCode: '1', flag: '🇺🇸' },
  { value: 'UY', label: 'Uruguay', dialCode: '598', flag: '🇺🇾' },
  { value: 'UZ', label: 'Uzbekistan', dialCode: '998', flag: '🇺🇿' },
  { value: 'VU', label: 'Vanuatu', dialCode: '678', flag: '🇻🇺' },
  { value: 'VA', label: 'Vatican', dialCode: '379', flag: '🇻🇦' },
  { value: 'VE', label: 'Venezuela', dialCode: '58', flag: '🇻🇪' },
  { value: 'VN', label: 'Vietnam', dialCode: '84', flag: '🇻🇳' },
  { value: 'WF', label: 'Wallis and Futuna', dialCode: '681', flag: '🇼🇫' },
  { value: 'EH', label: 'Western Sahara', dialCode: '212', flag: '🇪🇭' },
  { value: 'YE', label: 'Yemen', dialCode: '967', flag: '🇾🇪' },
  { value: 'ZM', label: 'Zambia', dialCode: '260', flag: '🇿🇲' },
  { value: 'ZW', label: 'Zimbabwe', dialCode: '263', flag: '🇿🇼' },
];